### ISSUE TITLE
Protocol TODO

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/display-bridge#1]
- [ ] Transmit clientID with request so we can send drop commands to the aircraft, terminating all subscriptions associated with that clientID
- [ ] Find a way to communicate desired precision for simvars (requires a32nx work)
- [ ] Investigate binary ws messages
